spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/jd?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    #    url: jdbc:mysql://101.32.200.73:3306/jd?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    #    username: gzh
    #    password: 123456
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小连接数
      minimum-idle: 5
      #空闲连接最大时间  默认600000（10分钟）
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      #连接最大存货时间  0表示永久存活  默认180000（30分钟）
      max-lifetime: 180000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 100000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接阻塞时间
        max-wait: 10000ms

        #最大空闲时间
        max-idle: 200




#mybatis-plus:
##  #配置Mapper.xml映射文件
##  mapper-locations: classpath*:/mapper/*Mapper.xml
#  #配置Mybatis数据返回类型别名（默认别名是类名）
#  type-aliases-package: com.jit.jd.pojo

##Mybatis  SQL打印（方法所在的包，不i是Mapper.xml所在的包）
#logging:
#  level:
#    com.xxx.jd.mapper: debug
#
#
server:
  port: 8081


  #rebbitmq配置
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest